version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - bigorders-network
    environment:
      - MONGODB_URI=mongodb://db:27017/bigorders

  db:
    image: mongo:latest
    restart: unless-stopped
    networks:
      - bigorders-network
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

networks:
  bigorders-network:
    driver: bridge

volumes:
  mongodb-data:
